### ISSUE TITLE
How to join the Organization?

### ISSUE THREAD

**Issue by EmpeRoar** [SurPathHub/support#12]
How to join the Organization?

**Comment by vinzvinci** [comment]
1. See the <a href="https://github.com/surpathcommunity/support/blob/main/README.md">guide</a>
2. Click **examples** & check the issue 
3. Create issues

**Done**
 > Wait for your invitation.

![image](https://user-images.githubusercontent.com/73097560/104282299-cd18cd80-54e9-11eb-8f5b-85015e0316f0.png)
