### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by Bryson69** [SurPathHub/support#17]
Invite me to the Surpath Community.

- #### Name: Bryson

- #### Discord Username(if exists): Bryson

- #### Additional Context: To learn more about open source

**Comment by vinzvinci** [comment]
Hello, thanks for your interest to join in our community. I'll put this `On hold` for now while the **GitHub Actions** isn't release yet.

**Comment by vinzvinci** [comment]
Hi bryson, thanks for your interest in our community. We know each other, and yeah only people from Philippines are allowed to join and be part of the community. See you in EddieHub Community, happy to assist you there :)
