### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by wardvisual** [SurPathHub/support#198]
### Name

Edward Fernandez

### Discord Username (if applicable)

 wardvisual#7461

### Additional Context

As the open-source community grows, I want to get involved and contribute to this awesome open-source community.

**Comment by gitakileus** [comment]
Name
akileus

Discord Username (if applicable)
akileus#5916

Additional Context
As the open-source community grows, I want to get involved and contribute to this awesome open-source community.
