### ISSUE TITLE
Change the version of COC to some of the repositories

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/support#20]
Copy our Code of Conduct 2.0: <a href="https://raw.githubusercontent.com/SurPathHub/starter-kit/main/CODE_OF_CONDUCT.md">https://raw.githubusercontent.com/SurPathHub/starter-kit/main/CODE_OF_CONDUCT.md</a>
~~-~~

Change the version of COC in these repositories: 
- <a href="https://github.com/SurPathHub/support">https://github.com/SurPathHub/support</a>
- <a href="https://github.com/SurPathHub/github-profile-ph">https://github.com/SurPathHub/github-profile-ph</a>
- <a href="https://github.com/SurPathHub/hacktoberfest-philippines">https://github.com/SurPathHub/hacktoberfest-philippines</a>
- <a href="https://github.com/SurPathHub/showcase-your-project">https://github.com/SurPathHub/showcase-your-project</a>
- <a href="https://github.com/SurPathHub/events-calendar">https://github.com/SurPathHub/events-calendar</a>

**Comment by srisatya1197** [comment]
@vinzvinci I want to work on this.

**Comment by vinzvinci** [comment]
Sure @srisatya1197, thank you 😄

**Comment by srisatya1197** [comment]
@vinzvinci in the COC 2.0 therer's no link for sm accounts. Should I add them while modifying in those repo's.

**Comment by vinzvinci** [comment]
Can you please elaborate @srisatya1197?

**Comment by srisatya1197** [comment]
@vinzvinci Yeah, I was saying that in the new version there's no social media accounts in the bottom of the readme file.

**Comment by vinzvinci** [comment]
@srisatya1197, no need for that. I already provided official email of SurPath Hub and even how will they mention the admin, moderator and the founder (me) in the discord Community.

**Comment by vinzvinci** [comment]
Up

**Comment by srisatya1197** [comment]
@vinzvinci Have a look in pr which I made. Is that right I just copied the code and pasted in the respective readme.

**Comment by vinzvinci** [comment]
Hi @srisatya1197, I'll check your PR later. Hmm I have suggestion, please edit the PR title related to what you did, for example: `Update COC version`

**Comment by srisatya1197** [comment]
@vinzvinci I'm sorry for that I'll change.

**Comment by srisatya1197** [comment]
@vinzvinci Sure.

**Comment by vinzvinci** [comment]
I cannot merge your PR @srisatya1197, please follow the directions:
- Don't edit the `README.md`
- Only Edit `CODE_OF_CONDUCT.md` file

**Comment by vinzvinci** [comment]
Thank you for doing this issue @srisatya1197 💯. I will close this issue now :)
