### ISSUE TITLE
Invite Me To The ORG

### ISSUE THREAD

**Issue by krishdevdb** [SurPathHub/support#29]
Invite me to the SurPath Hub Community.

- #### Name: Krish

- #### Country: India

- #### Discord Username(if exists): https://discord.com/invite/RATJsSGM9d

- #### Additional Context:

> 

>

**Comment by vinzvinci** [comment]
Thanks for your interest!

But sorry, this is a local community from the Philippines. I know you already part of the EddieHub community, you can look for their community partner if you want to join more community.
