### ISSUE TITLE
docs: add PR template

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/support#31]

**Comment by deephunt3r** [comment]
hey @vinzvinci can I added the same template which was added yesterday

**Comment by vinzvinci** [comment]
Sure @deephunt3r, we may edit the template you added soon.

**Comment by deephunt3r** [comment]
@vinzvinci I found the pr request template issue in remaining repo's so can I create pr directly?

**Comment by vinzvinci** [comment]
Better raise an issue first then go create PR directly @deephunt3r, just mention the issue that you're working. That's a good practice and you'll gain more 🟩 green squares (contributions).

**Comment by vinzvinci** [comment]
I'm allowing you to create PR directly this time, don't wait for my feedback on the issue. I will wait for your PR 👍
