### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by Lolimipsu** [SurPathHub/support#69]
### Name

MxLoli04

### Discord Username (if applicable)

MxLoli04

### Additional Context

my GitHub username is really Lolimipsu but I am referred to as MxLoli04 to GitHub and Discord.

**Comment by vinzvinci** [comment]
![too-cute-when-you-see-a-loli](https://user-images.githubusercontent.com/73097560/134767613-140a6c2f-c823-4a56-ab22-09923d1200d7.gif)

**Comment by vinzvinci** [comment]
![dancing-anime](https://user-images.githubusercontent.com/73097560/134767633-6d10c954-9f45-4cc0-92b2-613e9c067ce3.gif)

**Comment by Lolimipsu** [comment]
![PaleOpenFurseal-max-1mb](https://user-images.githubusercontent.com/44487404/134847097-e026a800-f75e-4ca6-98bc-74885a216125.gif)
